mobile.invalid.error.text = Incorrect phone number
email.invalid.error.text = We cannot find an account with that email address
email.enter.error.text = Enter your email or mobile phone number

password.invalid.error.text = Your password is incorrect
password.enter.error.text = 


account,list.text = Account & Lists
customerservice.text = Customer Service
amazonpay.text = Amazon Pay
today'sdeals.text = Today's Deals
all.text = All
prime.text = Prime
redmi.text = Redmi A2 (Sea Green, 2GB RAM, 64GB Storage)
subtotal.text = Subtotal (0 items):
search.invalid.error.text = No results for
 
cartempty.text = Your Amazon Cart is empty.
results.text = Results