mobile.lessthantendigit.text = 5858
mobile.specialcharacters.text = @%%#@#@
mobile.empty.text = 

password.invalid.specialcharacters.text = @#$%
password.empty.text = 
password.invalid.numbers.text = 738339

mobile.valid.text = 9908960579
password.valid.text = raviteja@6482

search.invalid.letters.tex= kdhfkjahk
search.invalid.numbers.text = 9999999999999999999999999
search.valid.casesensitiveletters.text = redMI moBIlE A2
search.valid.tvname.text = LG smart tv